### ISSUE TITLE
View Case Details - View Judge Information - Court Website

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#217]
User Story:
As an attorney assigned to the case, in order to easily file motions on a case, I want to be able to sign in the court's ECF system from CAMS.
Preconditions:
The case has been created in the court system and has been imported into DXTR Acceptance Criteria:
The user can navigate to the court's ECF system
It would be really cool if we could append whatever is needed to navigate directly to the case in the court's system.
** https://ecf.nysb.uscourts.gov/cgi-bin/qrySummary.pl?<CS_CASEID> Notes:
The court's URL is stored in AO_COURT_URL
** When querying this table there appear to be two rows per court. We need to determine which row to take. From quickly analyzing this, it appears that we could do latest, but we need to confirm. See the attachment for an example.
Figma link: https://www.figma.com/file/iTzW3lqGcWy4cEYaRDMOX3/Ch-15-Case-Info-Prototype-v1?type=design&node-id=12%3A181&mode=design&t=Bj3H2BFstKwbkWYO-1 Definition of Done:
Acceptance criteria met - The system meets all acceptance criteria
Feature toggles created - Features that are deployed but not released have toggles
Design QA passed - All visual UI looks and works the way it’s supposed to
Usability validated - Team ensures the working code is easy to use
Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
Code refactored for clarity - Developers can understand the work simply by reviewing the code
Dependency Rule followed - More important code doesn’t directly depend on less important code
Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
Source code merged - Code has been merged into the main branch
90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
Code reviewed - Code is reviewed by at least two other team members before being merged
Code quality checks passed - Code passes all automated quality checks
Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
Threat model updated - The threat model incorporates new threats and remediations 
Build process updated - Automated build process include code supporting the user story
Load/performance tests passed - Performance tests include the functionality of the user story
Documents are updated - All required documentation is up to date and version controlled
Code is deployed - Code is deployed to the highest production like environment

**Comment by jharcey-flexion** [comment]
Not gonna do it, wouldn't be prudent at this juncture.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-180 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
