### ISSUE TITLE
Notify the team when pipeline fails

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#255]
The team has not noticed when the pipeline has failed. We would like to notify them, so they can correct the issue.

Pre-Conditions:
  Acceptance Criteria:
 Notification is received by the team when the pipeline fails Pain Avoided/Frustration Saved:
  Breadth/Pervasiveness of Problem:
  Complexity of Problem (Low, Medium, High) and Why it's Complex:
  Notes
 

Need to find a good place to publish these, so that USTP staff can see it. Also want to make sure that it is not too noisy.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-54 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
