### ISSUE TITLE
View cases assigned to the user (trial attorney)

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#301]
## User Story:
As a Trial Attorney, I want to easily access the CAMS application and view the cases that I am assigned to, so that I can make sure I am paying attention to the relevant cases.

## Preconditions:
A bankruptcy case is available in CAMS
The case is assigned to the trial attorney
The trial attorney has authenticated into their computer

## Acceptance Criteria:
- [x] The trial attorney can easily view their chapter 15 caseload (cases that are assigned in CAMS).
~Tooltip on the case number is implemented~
- [x] My Cases Information modal is implemented

## Notes:
The intent of this story is to include SSO.
The intent is just to show the basic case information needed to identify the case. It is not expected that the trial attorney would be able to take any action on the case. ## Definition of Done: - [ ] Acceptance criteria met - The system meets all acceptance criteria
- [x] Feature toggles created - Features that are deployed but not released have toggles
- [ ] Design QA passed - All visual UI looks and works the way it’s supposed to
- [ ] Usability validated - Team ensures the working code is easy to use
- [x] Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
- [x] Code refactored for clarity - Developers can understand the work simply by reviewing the code
- [x] Dependency Rule followed - More important code doesn’t directly depend on less important code
- [x] Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [ ] Source code merged - Code has been merged into the main branch
- [x] 90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
- [x] Code reviewed - Code is reviewed by at least two other team members before being merged
- [x] Code quality checks passed - Code passes all automated quality checks
- [x] Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x] Threat model updated - The threat model incorporates new threats and remediations 
- [x] Build process updated - Automated build process include code supporting the user story
- [x] Load/performance tests passed - Performance tests include the functionality of the user story
- [x] Documents are updated - All required documentation is up to date and version controlled
- [ ] Code is deployed - Code is deployed to the highest production like environment

**Comment by samjohnsonflexion** [comment]
Friday 08/02/24. Brian/Fritz/Sam

- Added CamsUserReference type in session.ts

- Updated most tests to pass 
   - Added getCamsUserReference and getCamsUser functions in mock-data
   - Updated mock-users to include id
