### ISSUE TITLE
View history of attorneys assigned to a case

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#316]
User Story:
As an auditor, in order to know who was previously assigned to the case, I want to view history of the attorneys assigned to a case.
Preconditions:
A case exists
Acceptance Criteria:
The user can view history of the assignments.
** When an assignment is made or changed the data becomes available in the history
Notes:
the design can be found here: https://www.figma.com/file/iTzW3lqGcWy4cEYaRDMOX3/Ch-15-Case-Info-Prototype-v1?type=design&node-id=1388-1710&mode=design&t=k6YVHA5QkyBjlS9g-0

 ## Definition of Done:
- [x] Acceptance criteria met - The system meets all acceptance criteria
- [x] Feature toggles created - Features that are deployed but not released have toggles
- [x] Design QA passed - All visual UI looks and works the way it’s supposed to
- [x] Usability validated - Team ensures the working code is easy to use
- [x] Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
- [x] Code refactored for clarity - Developers can understand the work simply by reviewing the code
- [x] Dependency Rule followed - More important code doesn’t directly depend on less important code
- [x] Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [x] Source code merged - Code has been merged into the main branch
- [x] 90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
- [x] Code reviewed - Code is reviewed by at least two other team members before being merged
- [x] Code quality checks passed - Code passes all automated quality checks
- [x] Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x] Threat model updated - The threat model incorporates new threats and remediations 
- [x] Build process updated - Automated build process include code supporting the user story
- [x] Load/performance tests passed - Performance tests include the functionality of the user story
- [x] Documents are updated - All required documentation is up to date and version controlled
- [x] Code is deployed - Code is deployed to the highest production like environment

**Comment by fmaddenflx** [comment]
This issue needs detail, explanations, figma links, etc.
