### ISSUE TITLE
Refactor backend database module return object

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#331]
In the backend database.ts module, marked a couple TODOs to update the object structure of the return type from the execute query function. The following suggested changes was discussed:

On error, rethrow error instead of returning QueryResults
Returning message and success property may not make sense to return
Updated effected modules and tests

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-256 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
