### ISSUE TITLE
Display cases that are transferring

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#368]
User Story:
As a legal assistant tasked with processing DXTR data, in order to verify that a case is transferring from one court district to another, I want to view a list of cases that have a order transferring the case.
Preconditions:
The existing case is in DXTR
A order transferring the case from one court district to another is entered by the court
The order is received by DXTR
A transaction in AO_TX is created in DXTR indicating the case is being transferred
The case number is identified in the REC column
Acceptance Criteria:
The user can see a list of cases being transferred
Notes:
Transfer orders are indicated by TX_CODE = 'CTO' Here is an example:
CS_CASEID    COURT_ID    DE_SEQNO    CASE_ID    JOB_ID    TX_TYPE    TX_CODE    TX_DATE    REC    AO_TX_DISP    TX_DISP    TX_ID
316682    0208    111    23-22427    9244840    O    CTO    2023-10-07 07:22:09.8500000    O000000872322427CTO23100511000000        [11] 231005 23 WARN: 23-50607                                                            NULL    NULL    175977020
We will be creating a process to verify the transfer. After the transfer is confirmed in CAMS, the case would then be removed from this list. I think it will make sense to have a separate user story for not showing them.

**Comment by fmaddenflx** [comment]
move or rename lib/use-cases/gateway.types.ts

It's not clear what this was for.  Punted from CAMS-249.
