### ISSUE TITLE
View the old court district and case number

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#372]
User Story:
As an attorney, in order to know that a case has been transferred to or from another court district, I want to view the old or new court district and case number
Preconditions:
A case has been transferred and the new district and case number have been indicated
Acceptance Criteria:
The user can view the following:
** The old court district
** The old case number 
** When the case transferred
Notes:

**Comment by jharcey-flexion** [comment]
Deleted from Jira
