### ISSUE TITLE
View the order consolidating the case

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#377]
User Story:
As a legal assistant tasked with processing DXTR data, in order to know which cases are consolidating and which is the lead case, I need to view the order(s) consolidating the case.
Preconditions:
The cases are in DXTR
An order consolidating the case is entered by the court
The order is received by DXTR
A transaction in AO_TX is created in DXTR indicating the case is being consolidated Acceptance Criteria:
The user can view a summary of the case and the docket entries pertaining to the order consolidating the case. Notes:

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-271 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
