### ISSUE TITLE
Add an additional child case

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#381]
As an attorney monitoring the case, in order to ensure all cases that must be consolidated with the lead case are handled as such, I need to be able to add cases as child cases in the consolidation.
Preconditions:
The cases are in DXTR
An order consolidating the case is entered by the court
The order is received by DXTR
A transaction in AO_TX is created in DXTR indicating the case is being consolidated Acceptance Criteria:
The user can add additional cases that are the children cases
** The user can search for the additional case and basic information of the case would be returned to verify it is the case they want. Notes:
Sometimes the transaction in DXTR doesn't correctly identify all of the children cases, so we need a way to add additional cases.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-275 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
