### ISSUE TITLE
Remove completed consolidations

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#384]
User Story:
As a legal assistant tasked with processing DXTR data, in order to only see the cases I need to verify the consolidation of, I want cases that have been consolidated removed from the list
Preconditions:
A case has been consolidated and the type of consolidation, lead case, and children cases have been indicated Acceptance Criteria:
Cases that have already been consolidated do not show on the list to be consolidated Notes:

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-276 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
