### ISSUE TITLE
Display all cases in the office

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#398]
The intent is to remove the restriction that we currently have and deal with pagination 

All cases in this sense is to the feature flags for chapters. So all Chapter 15 when Chapter 11 and Chapter 12 are not enabled.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-287 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
