### ISSUE TITLE
View the full docket of the case that I am transferring

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#438]
User Story:
As a legal assistant tasked with data quality duties, in order to confirm the case is transferring, I want to easily navigate to and view the full docket of the case that I am transferring.
Preconditions:
The user is reviewing an order to transfer a case
A docket entry is being displayed
Acceptance Criteria:
The user can easily view the full docket for the case 
** Might be cool to go to the specific docket entry that created the order transaction - let's discuss. 
Notes:

**Comment by jharcey-flexion** [comment]
Deleted from Jira
