### ISSUE TITLE
Add additional security to Cosmosdb

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#452]
Pre-Conditions:
 Admin accounts are available to use Acceptance Criteria:
[ ] Justice.gov accounts can interact with Cosmos without entering their IP address
[ ] Maintain security posture
[ ] Only applies to Staging Pain Avoided/Frustration Saved:
Noticed that users that require access to CosmosDb need to add their ip to the allow list even when the user is accessing CosmosDb internally (with VPN). Updating the allow rule takes 10-15 minutes to take effect. Also, every time a deployment happens the firewall rules will need to be updated again. Breadth/Pervasiveness of Problem:
Impacts only the USTP staging environment. Complexity of Problem (Low, Medium, High) and Why it's Complex:
Medium. Notes

**Comment by jharcey-flexion** [comment]
Deleted from Jira
