### ISSUE TITLE
Develop pipeline workflow for full deployment

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#468]
Pre-Conditions:
  Acceptance Criteria:
USTP pipeline should have a workflow to run a full deployment
This workflow should not run the jobs related to slot deployment Pain Avoided/Frustration Saved:
Automation of new Azure resource creation and configuration when needed Breadth/Pervasiveness of Problem:
This will be needed when a new environment (set of Azure resources) is needed and/or significant infrastructure updates (like when new Azure resource is needed for CAMS) Complexity of Problem (Low, Medium, High) and Why it's Complex:
Low. Infrastructure as code already available. Workflow should already exist in the Flexion environment. Notes
Main workflow runs through a slot deploy workflow. Could modify existing workflow or at least document an approach to conduct a full deployment workflow that can enable deployment of infrastructure and code (slot deployment workflow limitation is that it may not be able to handle significant infra updates). 

Also, suggest that we convert our stage templates to job and/or step template instead.  
Definition of Done:
Acceptance criteria met - The system meets all acceptance criteria
Feature toggles created - Features that are deployed but not released have toggles
Design QA passed - All visual UI looks and works the way it’s supposed to
Usability validated - Team ensures the working code is easy to use
Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
Code refactored for clarity - Developers can understand the work simply by reviewing the code
Dependency Rule followed - More important code doesn’t directly depend on less important code
Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
Source code merged - Code has been merged into the main branch
90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
Code reviewed - Code is reviewed by at least two other team members before being merged
Code quality checks passed - Code passes all automated quality checks
Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
Threat model updated - The threat model incorporates new threats and remediations 
Build process updated - Automated build process include code supporting the user story
Load/performance tests passed - Performance tests include the functionality of the user story
Documents are updated - All required documentation is up to date and version controlled
Code is deployed - Code is deployed to the highest production like environment

**Comment by amorrow-flexion** [comment]
We can do approach this 2 different ways: 

1. We create a separate workflow that does a direct deployment, of both bicep executions and app component deployment.

-  pros
-- clear definition of what the pipeline does
-- does not add complexity to current deployment workflow
- cons
-- its a separate workflow 

2. We check the Build.Reason and modify current workflow to do a traditional nonslot deployment and bicep execution

- pros 
-- exists in the current workflow
- cons 
-- adds complexity to current workflow
