### ISSUE TITLE
Identify consolidated cases throughout app

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#470]
Need to identify consolidated cases throughout the system. One example is when a legal assistant is reviewing transfer orders, the user needs to be aware that it is a consolidated case, in order to properly transfer the case.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-321 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
