### ISSUE TITLE
Fix double API call on first page render for case detail and data verification

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#474]
Rejected because it is only occurring locally and not in running applications.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-323 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
