### ISSUE TITLE
Indicate data verification status on case docket

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#496]
User Story:
As an attorney monitoring a case, in order to ensure data is being updated on a case, I want to see the status of the data verification of an order on the case docket
Preconditions:
The case exists in CAMS
The order is received by DXTR
A transaction in AO_TX is created in DXTR indicating the case is being transferred
There are docket entries supporting the transfer in DXTR Acceptance Criteria:
The user can see the status of data verification of orders in the case docket. Notes:

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-330 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
