### ISSUE TITLE
Refactor backend repositories to leverage base class

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#524]
Pre-Conditions:
  Acceptance Criteria:
  Pain Avoided/Frustration Saved:
  Breadth/Pervasiveness of Problem:
  Complexity of Problem (Low, Medium, High) and Why it's Complex:
  Notes
CAMS-270 implementation introduce a new base class that provides new interfaces and reusable logic for accessing CosmosDb. Existing repository should be refactored with new interfaces and tested.

**Comment by jharcey-flexion** [comment]
Deleted from Jira
