### ISSUE TITLE
Screaming architecture for backend code

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#525]
Pre-Conditions:
  Acceptance Criteria:
  Pain Avoided/Frustration Saved:
  Breadth/Pervasiveness of Problem:
  Complexity of Problem (Low, Medium, High) and Why it's Complex:
  Notes
During peer review of CAMS-270, there were some discussion around improving the organization of the backend code for clarity.

**Comment by jharcey-flexion** [comment]
Deleted from Jira
