### ISSUE TITLE
Indicate which fields are required

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#546]
Purpose

Based on USWDS guidance, we want to clearly indicate which form fields are required, and which ones are optional. 

This ticket adds indicators to various form fields in CAMS (note: all of these are in the Data Verification section). Refer to the CAMS Master Prototype for clarification about any of these.

Going forward, similar styling should be applied to new required fields added to CAMS. The exception to this is when a form/modal has only a single input field; it does not need to be indicated as required.

See USWDS for more information. 

Acceptance Criteria

Required fields are marked with a Red (secondary-dark, #B50909) asterisk in the title of the field, with a space character between the title and the asterisk. 

If at least one field is marked as required, the help text "A red asterisk () indicates a required field." is present below above the group of fields. The asterisk in this sentence is the same Red. 

The following fields are marked as required:

The "New Court" and "New Case" fields in the Edit Case tab of a Transfer Case Event, in Data Verification (place the help text below the New Case field and above the selected case details, with appropriate padding).
The "Consolidation Type", "Lead Case Court", and "Lead Case Number" fields in the Additional Consolidation Information modal of a Consolidation Case Event, in Data Verification (place the help text below the Lead Case Number field and above the modal buttons, with appropriate padding).
 Definition of Done:
- [x] Acceptance criteria met - The system meets all acceptance criteria
- [x] Feature toggles created - Features that are deployed but not released have toggles
- [x] Design QA passed - All visual UI looks and works the way it’s supposed to
- [x] Usability validated - Team ensures the working code is easy to use
- [ ] Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
- [x] Code refactored for clarity - Developers can understand the work simply by reviewing the code
- [x] Dependency Rule followed - More important code doesn’t directly depend on less important code
- [x] Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [ ] Source code merged - Code has been merged into the main branch
- [x] 90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
- [x] Code reviewed - Code is reviewed by at least two other team members before being merged
- [ ] Code quality checks passed - Code passes all automated quality checks
- [ ] Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x] Threat model updated - The threat model incorporates new threats and remediations 
- [x] Build process updated - Automated build process include code supporting the user story
- [x] Load/performance tests passed - Performance tests include the functionality of the user story
- [x] Documents are updated - All required documentation is up to date and version controlled
- [ ] Code is deployed - Code is deployed to the highest production like environment

**Comment by fmaddenflx** [comment]
Put the notice above the form, as is required by USWDS.
