### ISSUE TITLE
Mirror ADO in GH

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#674]
## Pre-Conditions:
- ADO repo is sufficiently free of sensitive information
- GH private repo available

## Acceptance Criteria:
- [ ] All team members can access ADO updates
- [ ] Updates to ADO are automatically available in GitHub

## Pain Avoided/Frustration Saved:
- No need to share files periodically

## Breadth/Pervasiveness of Problem:
- Hard to access sometimes from some folks

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: Medium

Reason why is: Have to think about cadence, how much is copied/cloned/tracked upstream, permissions, security, etc.

**Comment by jharcey-flexion** [comment]
Deleted from Jira
