### ISSUE TITLE
Prevent a child case being a lead case

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#746]
As found while working CAMS-396, we need to prevent a user from making a case both the child and lead case. This is most likely to occur when there is one case in the order. 

This may not be an issue anymore - CAMS-405 could have resolved it.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-399 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
