### ISSUE TITLE
Fix Veracode SAST Scan & Upload intermittent failure

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#795]
## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: Low/Medium/High

Reason why is:

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-413 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
