### ISSUE TITLE
Bicep Improvements - App Config Keyvault infrastructure configuration

### ISSUE THREAD

**Issue by amorrow-flexion** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#813]
Currently, we do not include the setup of the keyvault private endpoint or keyvault itself within the main deployment workflow. We should include this configuration within main.bicep so we can avoid having to run this setup separately. 

## Acceptance Criteria:
- [ ] integrate keyvault configuration including private endpoint setup into main.bicep deployment 
- [ ] The main bicep contains all components (excluding sql and cosmos) required for a running CAMS environment 

## Pain Avoided/Frustration Saved:
- Clear segregation of resource responsibilities
- Would remove the need to do a partial keyvault setups before creating a new environment and final keyvault setup after initial deployment (which is how we have to do it currently)
- Deployment of a brand new application environment would be more straightforward, and everything would be clearly defined within main and cosmos bicep files instead of several bicep files.

## Breadth/Pervasiveness of Problem:

- It is fairly easy to misconfigure an environment as is. Other than the reference in documentation on the USTP side, it is not apparent that keyvault and its configuration is a predecessor to the application components when deploying an environment from scratch.
- Currently we have 3 base bicep files that are pertinent to the application environment: **main.bicep,  ustp-cams-cosmos.bicep, and ustp-cams-kv-app-config-setup.bicep** and 3 other auxiliary bicep templates: **ustp-cams-analytics-workspace.bicep, ustp-cams-cosmos-e2e.bicep, ustp-cams-sql.bicep** that are not required to have a functioning environment. This can be confusing to people (especially new people) working with the code. 
- The learning curve seems to be a pain point in the infrastructure. Minimizing and simplifying the bicep, as well as integrating KeyVault configuration with the current bicep will significantly reduce possibility of confusion and reduce the learning curve when approaching DevOps.

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: medium

## Notes:
- Do we also want to include Keyvault secrets, or keep these separate as they are? While deploying the secrets through bicep is convenient for config updates, it is a potential security risk having those run through a pipeline.

**Comment by jharcey-flexion** [comment]
duplicate
