### ISSUE TITLE
Bicep Improvements - Logging (App Insights) and Alert modularization

### ISSUE THREAD

**Issue by amorrow-flexion** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#814]
We don't necessarily need to deploy all app insights resources. e.g. USTP already has a designated Log Analytics workspace, Action Groups, and log storage resources. So, it would be best to pull that setup into their own .bicep instead of tacked on to the frontend and backend resource provisioning.  

This would also allow us to properly configure branch deployments with application insights on initial deployment and remove a small bit of complexity within the bicep.

## Acceptance Criteria:
- [ ] App Insights/alert modules are separated from frontend and backend bicep execution and in their own template referenced in main.bicep 

## Pain Avoided/Frustration Saved:
- Allows us to properly configure App Insights on initial branch deployment and simplifies structure of bicep code
- Helps Create Clear definition of Infrastructure within the bicep

## Breadth/Pervasiveness of Problem:
- Deployment of a brand new application instance would be more straightforward, and everything would be clearly defined within main.bicep instead of separate bicep files

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: low

**Comment by jharcey-flexion** [comment]
duplicate
