### ISSUE TITLE
Display all cases in the office on the Staff Assignment view

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#822]
## User Story:
As an AUST, in order to assign staff to cases in my office, I need to be able to see all the cases my office is overseeing.

The intent of this is to remove the number of cases limitation we currently have. 

## Preconditions:
- We can determine who the AUST is in an office

## Acceptance Criteria:
- [x] Given an AUST (or a yet to be determined role who is responsible for assigning cases) is logged in, when the user accesses the case assignment view, then the list of all chapter 15 cases that belong to that office is displayed.  
- [x] Chapter 12 cases are displayed, only if the Chapter 12 feature flag is enabled.
- [x] Chapter 11 cases are displayed, only if the Chapter 11 feature flag is enabled.

## Notes:
- Other stories will implement any filtering or sorting.
- When we began implementing CAMS-48 we decided to use the Case Search grid as a starting point, because it was newer, cleaner code. We discussed possibly using the same pattern for the case assignment screen. 
- Jon thinks of the case assignment screen kind of like a my cases view for AUSTs. The AUST is responsible for all the cases in their office. 

## Definition of Done:
- [ ] Acceptance criteria met - The system meets all acceptance criteria
- [ ] Feature toggles created - Features that are deployed but not released have toggles
- [ ] Design QA passed - All visual UI looks and works the way it’s supposed to
- [ ] Usability validated - Team ensures the working code is easy to use
- [x] Accessibility tests passed - System passes automated and manual accessibility tests and supports applicable devices
- [x] Code refactored for clarity - Developers can understand the work simply by reviewing the code
- [x] Dependency Rule followed - More important code doesn’t directly depend on less important code
- [x] Development debt eliminated - UX and code aligns to the team’s latest understanding of the domain
- [x] Source code merged - Code has been merged into the main branch
- [x] 90% unit test coverage achieved - Automated test coverage tools indicate coverage of >= 90%
- [x] Code reviewed - Code is reviewed by at least two other team members before being merged
- [x] Code quality checks passed - Code passes all automated quality checks
- [x] Security scans passed - Code passes expected scans for vulnerabilities and compliance issues
- [x] Threat model updated - The threat model incorporates new threats and remediations 
- [x] Build process updated - Automated build process include code supporting the user story
- [x] Load/performance tests passed - Performance tests include the functionality of the user story
- [x] Documents are updated - All required documentation is up to date and version controlled
- [ ] Code is deployed - Code is deployed to the highest production like environment

**Comment by jharcey-flexion** [comment]
Notes: https://docs.google.com/document/d/1NUnLoqJ5UobIyHTFAMCSgdpAUrrg2eZ3J8zuGFuU1u0/edit?usp=drive_link
