### ISSUE TITLE
Address Case Detail Non-critical Accessibility Issues (Part 1)

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#858]
- [x] Look at H1 with name of page. Page is not titled, Perhaps should be Case Details
- [x] Remove Back Link 
  ~Correct the Back to case list link. Could we know where the user came from to go back? Could be coming from My Cases, Staff Assignment, or Case Search.~
- [x] Rename Basic Information to Case ~Details~ Overview?
- [x] Rename Audit History (Audit has baggage)
- [x] Display the division code somewhere
- [x] fix the space between labels and data.
- [x] Change History empty state alert (no changes made) should say "No changes have been made to this case."

**Comment by amorrow-flexion** [comment]
Couple of questions
1. back to case list link: We click a link when navigating to Case Detail Screen and open it in a new tab, why is this even really necessary when the previous tab is still open and the nav options are available to the user?
2. Basic Information to Case Summary?
3. specify what to fix for labels and data?

**Comment by ShallieDragon** [comment]
1. H1 should be Case Details - [Case name], and Basic Information should become Case Overview.
2. That's a good question, that I will need to follow up on. Opening in a new tab should probably be an option, not necessarily the default behavior. I can circle back on that. 
3. "Audit History" is becoming "Change History". 
4. The issue is that we are currently not displaying division code anywhere in the app (intentionally). So, I figured the best place to put it was in the case number header for the Case Details of the case in question. That way, it's somewhere obvious, for people who need it.

**Comment by amorrow-flexion** [comment]
2. Opening in a new tab, erases current tab context history which would increase complexity for a back button. So, if we want both pieces of functionality I believe this should be it's own ticket, not associated with this one.

4. My other thought on this was to put it by the Court Division Name in Case Detail to keep it close to the data it represents. See Screenshot below:

![image](https://github.com/user-attachments/assets/35641b0c-91f4-40d8-b56f-42de453ad00f)

**Comment by ShallieDragon** [comment]
I'll follow up on the "should we open in a new tab" thing. 

Re: division code, I think we should keep the full case number as one object. Reason being is that the full case number is often selected for copy-paste into other applications (e.g. FICS), and having it all together makes that much easier.

**Comment by fmaddenflx** [comment]
So to clarify ShallieDragon, we should set H1 to which of the following?:

1. Case Details - [Case name]
2. Case Details - [Case name] Case Overview
3. Case Details - [Case name] - Case Overview

**Comment by ShallieDragon** [comment]
> So to clarify ShallieDragon, we should set H1 to which of the following?:
> 
>     1. Case Details - [Case name]
> 
>     2. Case Details - [Case name] Case Overview
> 
>     3. Case Details - [Case name] - Case Overview

The first one.

**Comment by fmaddenflx** [comment]
"fix the space between labels and data"

What do we mean here by "fix" ?

Is the following satisfactory?
<img width="792" alt="Screenshot 2024-09-16 at 2 43 42 PM" src="https://github.com/user-attachments/assets/6c68a34f-68f6-4311-9faa-ccf35b1d6349">

**Comment by fmaddenflx** [comment]
"fix the space between labels and data"

What do we mean here by "fix"?

Is the following satisfactory?

<img width="710" alt="Screenshot 2024-09-16 at 2 46 10 PM" src="https://github.com/user-attachments/assets/b512ecf6-fd7e-4aba-a964-63b034034b09">

**Comment by ShallieDragon** [comment]
Oh I think I know what the issue was. There were some fields where there was no space between the label and the value (so, "Order Filed:06/20/2010" instead of "Order Filed: 06/20/2010"). We wanted to make sure a whitespace character was inserted between field labels and values.

**Comment by fmaddenflx** [comment]
Okay cool.  Already took care of that.

**Comment by fmaddenflx** [comment]
This item:  "Change History empty state alert (no changes made) should say "No changes have been made to this case.""

I'm not seeing any alert that says "no changes made".  

I do see an alert that says "There are no assignments in the case history.".  Is this the one we're talking about?

**Comment by ShallieDragon** [comment]
Correct, that is the one we want to change. The parentheses were describing the purpose of the alert, not its text (sorry for the confusion).

**Comment by jamesobrooks** [comment]
Regarding the opening of a new tab for going to case details, opening in a new tab is always an option through keyboard or mouse. The reason we made it always open in a new tab was to not interrupt the user's workflow on the screen they are on. Certainly for staff assignment this might be less of an issue than with data verification because staff assignment can be performed on the case details screen, so maybe we change that one screen's links, but I just wanted to make sure we're not losing sight of why it is the way it is.

**Comment by fmaddenflx** [comment]
On the latest PR, I implemented a way to keep track of the original tab, such that when clicking on the back link, it takes you back to that original tab.  It does however, refresh that tab, so any work the user was in the middle of would be reloaded.

The tab name is refreshed with each login and is unique to that login.

**Comment by ShallieDragon** [comment]
Currently, that shouldn't be a problem. We don't have any changes that need to be made, that couldn't be easily replicated on a page refresh. When that is no longer the case, though, we'll want to investigate some way for CAMS to save "draft" states for certain systems. But that's down the road a ways, I think.

**Comment by fmaddenflx** [comment]
Do to a long list of potentially disorienting behavior as a result of trying to control the back link, we decided it was best to remove it entirely.  There are too many edge cases with usability.
