### ISSUE TITLE
Update "Staff Assignment" to be called "Case Assignment"

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#910]
There has been some confusion about whether we refer to our assigning staff tool as Staff Assignment or Case Assignment. For the sake of being consistent with ACMS, this ticket will update the locations where CAMS says "Staff Assignment" to say "Case Assignment." 

Note: we may decide that this is not necessary, and that Staff Assignment is the preferred term. If so, we should inform Lara that we want to say Staff Assignment in our help documentation.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-439 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
