### ISSUE TITLE
Switch Prod Pipeline to not deploy based on time

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#921]
## Pre-Conditions:
- The app has gone live for users.

## Acceptance Criteria:
- [ ] Production pipeline will not deploy automatically each day based only on a schedule.

## Pain Avoided/Frustration Saved:
- It is possible that code and infrastructure that deploy successfully and work in the Flexion dev environment will fail to deploy and work in the USTP environment.
 - If a deployment to staging has not succeeded and been validated, we should not deploy to production.

## Breadth/Pervasiveness of Problem:
- One pipeline

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: Low

Reason why is: The simplest approach here is to disable the scheduled deployment and only run a deployment manually after verifying that a deployment to staging was successful.

## Notes:
If we were to get e2e and/or smoke tests running in staging, we could easily move to just one pipeline with a production deployment following after validation of a staging deployment.

**Comment by jamesobrooks** [comment]
We'll just stop the automated deployment for now.
