### ISSUE TITLE
Allow interaction with Data Explorer for CosmosDb in USTP env

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#957]
## Pre-Conditions:
- CosmosDb exists in USTP env and the user has access

## Acceptance Criteria:
- [x] Access not overwritten with deployment
- [x] Should work on any subnet in USTP environment
- [x] Allows admin user to create, update, delete records

## Pain Avoided/Frustration Saved:
- No longer have to make network changes for individual IP addresses and wait for app to restart

## Breadth/Pervasiveness of Problem:
- Every time we want to make a db change after a deployment

## Complexity of Problem (Low, Medium, High) and Why it's Complex:
Complexity is: Low

Reason why is: we have already done this, it would just be for additional subnets.

##NOTE
- Azure middleware IP addresses do rotate and the bicep settings will need to be updated when they do

**Comment by amorrow-flexion** [comment]
Have branch open ready for merge if we would like, but CAMS-442 will conflict with this, so I moved the changes there
