### ISSUE TITLE
Manual data migration

### ISSUE THREAD

**Issue by governmentSponsored** [US-Trustee-Program/Bankruptcy-Oversight-Support-Systems#969]
for consolidations, assignments, etc.
For now, only open cases for chapter 15. Later on we will bring in historical (7 years after close) case info.

**Comment by jharcey-flexion** [comment]
Correcting close reason from Completed to Not Planned. CAMS-458 was rejected in the Jira backlog. Corrected as part of a repo-wide DORA-metrics audit reconciling GitHub issue state against the authoritative Jira disposition.
